[package]
name = "gitultra-schemas"
version = "0.1.0"
repository.workspace = true
edition.workspace = true

[lib]
name = "gitultra_schemas"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
flatbuffers = "25.2.10"

[build-dependencies]
flatbuffers = "25.2.10"
