[package]
name = "core-lib"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
git2.workspace = true
redb = { workspace = true, features = ["logging", "cache_metrics"] }
thiserror = "2.0.12"
flatbuffers = { workspace = true }
gitultra-schemas = { path = "../../packages/schemas"}
tauri.workspace = true
tauri-plugin-store.workspace = true
log = "0.4.26"
specta = {workspace = true, features = ["derive"]}
serde = {version =  "1.0.219", features = ["derive", "std"] }
